app = "clickdog"
primary_region = "arn"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  BOT_TOKEN = "8065777167:AAFQGwJHGoaXgFkt4DQq7veaMU7IPEWXwHk"

[[mounts]]
  source = "bot_data"
  destination = "/data"

[processes]
  app = "python bot.py"