app = "my-telegram-bot-asus123"
primary_region = "ru"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  BOT_TOKEN = ""

[[mounts]]
  source = "bot_data"
  destination = "/data"

[processes]
  app = "python bot.py"